// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo8EFxa2jK6YEsL8xbLO1xXpFB4QdtZto',
    appId: '1:736649773651:web:65c248f92ca2c60e2e3ca6',
    messagingSenderId: '736649773651',
    projectId: 'wismod-5464e',
    authDomain: 'wismod-5464e.firebaseapp.com',
    storageBucket: 'wismod-5464e.appspot.com',
    measurementId: 'G-LYKSNV3VHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApc1UH8GWZ4aaB1VY5jRFeKgzV2xKCCc0',
    appId: '1:736649773651:android:a92d18d3d915bfb12e3ca6',
    messagingSenderId: '736649773651',
    projectId: 'wismod-5464e',
    storageBucket: 'wismod-5464e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxMjrWs1ZTEk2aWf46I9_cNyZ0yg7qpoo',
    appId: '1:736649773651:ios:af0fb2d780dfe13d2e3ca6',
    messagingSenderId: '736649773651',
    projectId: 'wismod-5464e',
    storageBucket: 'wismod-5464e.appspot.com',
    iosClientId: '736649773651-s4c7210s5gn6baqmalo6e72o01ipe0be.apps.googleusercontent.com',
    iosBundleId: 'com.example.wismod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxMjrWs1ZTEk2aWf46I9_cNyZ0yg7qpoo',
    appId: '1:736649773651:ios:af0fb2d780dfe13d2e3ca6',
    messagingSenderId: '736649773651',
    projectId: 'wismod-5464e',
    storageBucket: 'wismod-5464e.appspot.com',
    iosClientId: '736649773651-s4c7210s5gn6baqmalo6e72o01ipe0be.apps.googleusercontent.com',
    iosBundleId: 'com.example.wismod',
  );
}
